version: "v3"

# Enable inputbox to submit flag: true | false
enable_flag_input: false

crp_type: "docker"

crp_config:
    controller:
        ports: ["5555/controller"]
        read_only: true
    solvable:
        # Required Linux capabilities (See http://man7.org/linux/man-pages/man7/capabilities.7.html for the full list).
        capabilities: ["SETGID", "SETUID", "AUDIT_WRITE"]
        mem_limit_mb: 200 # Only set this if the default 100 MB is not enough (max 1024 MB)
        ports: ["8888/http"]
        read_only: true
