---
pipeline:
  build:
    image: docker
    when:
      branch: v3
    commands:
      - docker build --pull -t eu.gcr.io/avatao-challengestore/challenge-builder:${DRONE_BRANCH} .
      - docker push eu.gcr.io/avatao-challengestore/challenge-builder:${DRONE_BRANCH}
    volumes:
      - /etc/docker:/etc/docker:ro
      - /root/.docker:/root/.docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
