version: "v3"

#Enable inputbox to submit flag: true | false
enable_flag_input: true

# If the solution is a fix string (static flag) you can add it here.
flag: "SaH{wh4t_4n_EXCLUSIVE_ch4llenge_they_sur3_SW1TCHED_th1ngs_up_a_bit_ahaha_get_1t?}"

crp_type: "docker"

crp_config:
    controller:
        ports: ["5555/controller"]
    solvable:
        # Required Linux capabilities (See http://man7.org/linux/man-pages/man7/capabilities.7.html for the full list).
        # For example ["SETGID", "SETUID"]
        # capabilities: [] # Not needed if empty
        ports: ["8888/tcp"]
