version: v3.2
flag: 'SaH{Th3_b3st_part_1s_h4ving_to_type_in_all_th1s_text_403fccc83712f4084a3e5df3f576617c}'
enable_flag_input: true
downloads:
  - "https://downloads.avatao-challenge.com/manual/handout.tar.gz"
