version: v3.2

# Enable inputbox to submit flag: true | false
enable_flag_input: false

# If the solution is a fix string (static flag) you can add it here.
# flag: "This_iS_the_Solution"

crp_type: "docker"

crp_config:
    controller:
        # Required Linux capabilities (See http://man7.org/linux/man-pages/man7/capabilities.7.html for the full list).
        # For example ["SETGID", "SETUID"]
        #capabilities: [] # Not needed if empty
        ports: ["5555/controller"]
        read_only: true
    solvable:
        #capabilities: [] # Not needed if empty
        ports: ["8888/http"]
        read_only: true
