version: v3.2

#Enable inputbox to submit flag: true | false
enable_flag_input: true

# If the solution is a fix string (static flag) you can add it here.
flag: "doctor@177.143.65.198"

crp_type: "docker"

crp_config:
    controller:
        ports: ["5555/controller"]
        read_only: true
    solvable:
        # Required Linux capabilities (See http://man7.org/linux/man-pages/man7/capabilities.7.html for the full list).
        # For example ["SETGID", "SETUID"]
        # capabilities: [] # Not needed if empty
        ports: ["2222/ssh"]
        read_only: true
